services:
  postgres:
    image: postgres:17.4
    platform: linux/arm64
    env_file:
      - .env
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data_platform_network

  pgadmin:
    image: elestio/pgadmin
    platform: linux/arm64
    env_file:
      - .env
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./services/pgadmin/config/servers.json:/pgadmin4/servers.json
    networks:
      - data_platform_network

  initializer:
    build:
      context: .
      dockerfile: services/initializer/Dockerfile
    env_file:
      - .env
    container_name: initializer
    depends_on:
      - postgres
    volumes:
      - initializer_data:/app
    networks:
      - data_platform_network

networks:
  data_platform_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  initializer_data:
