services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    platform: linux/arm64
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      # Podmiana domyślnego pliku konfiguracyjnego na nasz własny
      - ./config/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      # Miejsce na dane bazy – trwały zapis na hoście
      - ./data/postgres:/var/lib/postgresql/data
    # Nadpisujemy domyślną komendę uruchamiając Postgresa z naszym plikiem konfiguracyjnym
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - data_platform_network

networks:
  data_platform_network:
    driver: bridge
